language: ruby
rvm:
  - 2.3.3
sudo: required

# no emails
notifications:
  email: false

# asciidoctor diagram dependencies
before_install:
  - sudo apt-get install -y graphviz ditaa plantuml

# build the site
script:
  - bundle exec jekyll build

# upload to the master branch
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  local-dir: _site
  target-branch: master
  verbose: true
  on:
    branch: develop
