language: ruby
rvm:
  - 2.3.3
sudo: required

# asciidoctor diagram dependencies
before_install:
  - sudo add-apt-repository -y ppa:jasekpetr/trusty-backports
  - sudo add-apt-repository -y ppa:jonathonf/rustlang
  - sudo apt-get -qq update
  - sudo apt-get install rustup cargo
  - rustup
  - cargo install svgbob_cli
  - sudo apt-get install -y graphviz ditaa plantuml

# build the site
script:
  - bundle exec jekyll build

# upload to the master branch
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  local-dir: _site
  target-branch: master
  verbose: true
  on:
    branch: develop
