language: ruby
cache: bundler
rvm:
  - 2.3.3
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:isage-dna/plantuml
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz ditaa plantuml

script:
  - bundle exec jekyll build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  local-dir: _site
  target-branch: master
  on:
    branch: develop
