name: ane
description: programming
meta_description: "A personal programming-oriented blog of Antoine Kalmbach."

encoding: utf-8
markdown: redcarpet
excerpt_separator: <!--break-->
logo: false
paginate: 3
baseurl: /
domain_name: 'http://ane.iki.fi/'
highlighter: pygments

# Details for the RSS feed generator
url:            'http://ane.iki.fi/'
author:         'Antoine Kalmbach'
google_analytics: UA-58162697-1
redcarpet:
  extensions: ["footnotes", "fenced_code_blocks", "strikethrough", "autolink", "superscript", "highlight", "underline", "quote", "with_toc_data", "tables"]
