name: Antoine Kalmbach
description: Antoine Kalmbach's Blog
meta_description: "The personal blog of Antoine Kalmbach, a Finnish-French software engineer."
encoding: utf-8
excerpt_separator: <!--break-->
logo: false
markdown: kramdown
mathjax: true
paginate: 3
exclude: ["vendor"]
baseurl: ""
domain_name: 'http://ane.github.io'
highlighter: rouge

# Details for the RSS feed generator
url:            'http://ane.github.io'
author:         'Antoine Kalmbach'
google_analytics: UA-58162697-1
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions

twitter:
  username: anewtf

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
